### ISSUE TITLE
Best Lib

### ISSUE THREAD

**Issue by karmamaster** [mringwal/mouse-support#3]
yes

**Comment by mringwal** [comment]
Hi. MouseSupport provides a CFMessagePort with the id "jp.ashikase.mousesupport". 

To send mouse events, you need to connect to this CFMessagePort and sent it packets of type MouseEvent on the iOS device.

Here (and in the beginning of Tweak.xm) is the typeder:

typedef struct {
    float x, y;
    int buttons;
    BOOL absolute;
} MouseEvent;

x & y are in screen coordinates. buttons = 1 means button down, and absolute indicates coordiates relative to the top/left instead of the last location.

I don't know if you can compile c# for iOS. If not, you would need to provide some kind of daemon that allows you to connect to a fixed TCP/IP port to send messages that then forwards them to mouse-support.

I don't know if you can use VNC without sending the images back to the PC. If yes, you could use saurik's Veency that provides a VNC server (I think VNC uses UDP) and forwards the mouse movements to mouse-support instead of writing your own deamon.

**Comment by karmamaster** [comment]
yes

**Comment by mringwal** [comment]
you don't need to compile it your self or load it via dlopen. You only need to connect to the CFMessagePort. Feel free to have a look at the libhid-support of my hid-support package (also on github) for boring code that connects to a CFMessagePort. Also, you might need to use RocketBootstrap to make it work at least for regular apps. (also used in libhid-support)

**Comment by karmamaster** [comment]
yes

**Comment by karmamaster** [comment]
yes

**Comment by karmamaster** [comment]
yes

**Comment by mringwal** [comment]
hi. hid-support can simulate touch events but doesn't show a mouse pointer. I've never implemented that.

if you need a visible mouse pointer, please use CFMessagePort to talk to mouse-support tweak as explained before.

if you only need to simulate touches, please use hid-support by adding the libhid-support.h to your project and link against libhid-support.dylib. You can get libhid-support.dylib from your jailbreak device it's in /usr/local/lib or /usr/lib.

If you get undefined symbols in hidsupportest, please check the your libhid-support.dylib and try with the one from your device. I'd bet they are there. (I cannot check/test, hid-support doesn't compile for me right now and I don't have time to look into my setup currently. no JB dev since a long time).

**Comment by karmamaster** [comment]
Thank you so much Mringwal, I will be back with the result

**Comment by karmamaster** [comment]
Hello Mr. Mringwal,
I have code a function like this to send message to mouse support:

**Comment by mringwal** [comment]
Looks about right. When you define a local variable like even in mouse_open(), it is not initialized at all. So, if x or y are negative or outside, it won't work. You could add event.x=100 and event.y=100 here.

I think you should first send MouseMessageTypeSetEnabled to make it visible.

Ah.. saurik's veency uses it and the code is here:
https://github.com/faywong/veency/blob/master/Tweak.mm

Please try to extract the code to send mouse events from there.

**Comment by karmamaster** [comment]
Thanks Mr. Mringwal,
You have my best respect as a brother, Now I can control the mouse-support as i wanted. 
Thanks very much

**Comment by mringwal** [comment]
You're welcome. Have fun!
